services:
  - type: web
    name: arnhem-flights-api
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arnhem-flights-db
          property: connectionString

  - type: worker
    name: arnhem-flights-collector
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python collector.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arnhem-flights-db
          property: connectionString

databases:
  - name: arnhem-flights-db
    plan: free
