services:
  - type: web
    name: arnhem-flights-api
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arnhem-flights-db
          property: connectionString

databases:
  - name: arnhem-flights-db
    plan: free
